[package]
name = "url-shortener"
version = "0.1.0"
authors = ["Majedul Hoque <rumanbsl@gmail.com>"]
edition = "2018"

[dependencies]
hyper="0.12.29"
futures="0.1.27"
log="0.4.6"
pretty_env_logger="0.3.0"
rust-crypto="0.2.36"
lazy_static="1.3.0"
serde_json="1.0.39"